name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
        components: rustfmt, clippy

    - name: Cache Rust dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: instruction-set-analyzer-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          instruction-set-analyzer-cargo-

    - name: Run rustfmt
      run: cargo fmt --all -- --check

    - name: Run clippy
      run: cargo clippy --all-targets --all-features -- -D warnings

    - name: Build
      run: cargo build --all-features --verbose

    - name: Run tests
      run: cargo test --all-features --verbose

    - name: Run cargo check
      run: cargo check --all-features
